name: Run

on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: docker version
        run: docker version
      - name: clone
        uses: actions/checkout@v3
      - name: docker build
        run: docker build .
      - name: docker run
        run: docker run -t $(docker build -q .)
