name: Run

on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  #, windows-latest]
    steps:
      - name: start docker on windows
        if: runner.os == 'Windows'
        run: Start-Service docker    
      - name: install docker on macos
        if: runner.os == 'macOS'
        run: |
          brew install --cask docker
          echo STARTING
          open /Applications/Docker.app
          sleep 3
          docker version && echo OK || echo NOPE
          sleep 600
      - name: docker version
        run: docker version
      - name: clone
        uses: actions/checkout@v3
      - name: docker build
        run: docker build . -t demo
      - name: docker run
        run: docker run demo
